### ISSUE TITLE
Seneca.js

### ISSUE THREAD

**Issue by blainsmith** [gk-brown/WebRPC#1]
I like the WebRPC stuff. This is actually being exposed with http://senecajs.org too if you have not seen it yet. Under the hood the transport doesn't matter, but the core service not only does RPC within processes, but also has a "web" component it will listen to for commands. Thought I would put it on your radar if you wanted to check it out.

**Comment by gk-brown** [comment]
Thanks for checking out WebRPC. So is Seneca.js using WebRPC under the hood, or does it just do something similar? I'm guessing the latter - just wanted to make sure I understood.
